### ISSUE TITLE
how to get the pose matrix of camera?

### ISSUE THREAD

**Issue by ZMIOT** [iory/texture-mapping#2]
hi iory ,how to get the pose matrix of camera?
```
translation_x translation_y translation_z
rotation_00 rotation_01 rotation_02
rotation_10 rotation_11 rotation_12
rotation_20 rotation_21 rotation_22
```
How are these parameters obtained?
thank you!

**Comment by iory** [comment]
Hi.
I made the robot hold the object and moved it.
The poses can be obtained from the relative relationship between the robot's posture and the camera.
