### ISSUE TITLE
Understanding Documentation

### ISSUE THREAD

**Issue by MGforest** [iory/texture-mapping#4]
Hi, 
Your code seems really helpful. However, I donnot fully understand the config file: 
```
translation_x translation_y translation_z
rotation_00 rotation_01 rotation_02
rotation_10 rotation_11 rotation_12
rotation_20 rotation_21 rotation_22
fx
fy
cx
cy
image_height
image_width
```

What exactly is **fx, fy, cx and cy**?

Thank your very much in advance!

**Comment by iory** [comment]
Thanks for your questions.
They are camera parameters.
https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html

**Comment by MGforest** [comment]
Thank you for your quick answer!
For anyone else: 
 focal length ( fx,fy) and optical centers ( cx,cy)
 
 Do I understand correctly that the units are in cm and degree (not radiant)?

**Comment by iory** [comment]
> focal length ( fx,fy) and optical centers ( cx,cy)

That's right.

> the units are in cm and degree (not radiant)?

That's not right. OpenCV documents may help you.

> Where (X, Y, Z) are the coordinates of a 3D point in the world coordinate space, (u, v) are the coordinates of the projection point in pixels. A is called a camera matrix, or a matrix of intrinsic parameters. (cx, cy) is a principal point (that is usually at the image center), and fx, fy are the focal lengths expressed in pixel-related units. 

http://opencv.jp/opencv-2svn_org/c/calib3d_camera_calibration_and_3d_reconstruction.html

**Comment by iory** [comment]
> focal length ( fx,fy) and optical centers ( cx,cy)

That's right.

> the units are in cm and degree (not radiant)?

That's not right. opencv document's mey help you.

> Where (X, Y, Z) are the coordinates of a 3D point in the world coordinate space, (u, v) are the coordinates of the projection point in pixels. A is called a camera matrix, or a matrix of intrinsic parameters. (cx, cy) is a principal point (that is usually at the image center), and fx, fy are the focal lengths expressed in pixel-related units. 

http://opencv.jp/opencv-2svn_org/c/calib3d_camera_calibration_and_3d_reconstruction.html

**Comment by MGforest** [comment]
Thanks!
So f and c are in pixel. 

What I got from searching on the internet is, that the angles in the rotation matrix are in degree.
